2023/07/27 07:45:42 [error] 32#32: *2 open() "/etc/nginx/html/favicon.ico" failed (2: No such file or directory), client: 218.39.165.81, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "58.180.5.178:43015", referrer: "http://58.180.5.178:43015/"
2023/07/27 08:10:18 [crit] 29#29: *1 connect() to unix://srv/django/django.sock failed (2: No such file or directory) while connecting to upstream, client: 218.39.165.81, server: localhost, request: "GET / HTTP/1.1", upstream: "uwsgi://unix://srv/django/django.sock:", host: "58.180.5.178:43015"
2023/07/27 08:19:26 [crit] 29#29: *1 connect() to unix://srv/django/django.sock failed (2: No such file or directory) while connecting to upstream, client: 218.39.165.81, server: localhost, request: "GET / HTTP/1.1", upstream: "uwsgi://unix://srv/django/django.sock:", host: "58.180.5.178:43015"
2023/07/27 08:19:28 [crit] 29#29: *1 connect() to unix://srv/django/django.sock failed (2: No such file or directory) while connecting to upstream, client: 218.39.165.81, server: localhost, request: "GET / HTTP/1.1", upstream: "uwsgi://unix://srv/django/django.sock:", host: "58.180.5.178:43015"
2023/07/27 09:23:56 [crit] 29#29: *1 connect() to unix://srv/django/django.sock failed (2: No such file or directory) while connecting to upstream, client: 218.39.165.81, server: localhost, request: "GET / HTTP/1.1", upstream: "uwsgi://unix://srv/django/django.sock:", host: "58.180.5.178:43015"
2023/07/28 02:40:29 [crit] 30#30: *4 connect() to unix://srv/django/django.sock failed (2: No such file or directory) while connecting to upstream, client: 218.39.165.81, server: localhost, request: "GET / HTTP/1.1", upstream: "uwsgi://unix://srv/django/django.sock:", host: "58.180.5.178:43015"
2023/07/28 02:40:35 [crit] 30#30: *4 connect() to unix://srv/django/django.sock failed (2: No such file or directory) while connecting to upstream, client: 218.39.165.81, server: localhost, request: "GET /admin HTTP/1.1", upstream: "uwsgi://unix://srv/django/django.sock:", host: "58.180.5.178:43015"
2023/07/28 02:41:08 [crit] 30#30: *4 connect() to unix://srv/django/django.sock failed (2: No such file or directory) while connecting to upstream, client: 218.39.165.81, server: localhost, request: "GET /media/images_4.jpg HTTP/1.1", upstream: "uwsgi://unix://srv/django/django.sock:", host: "58.180.5.178:43015"
2023/07/28 09:47:43 [crit] 30#30: *1 connect() to unix:/app/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 218.39.165.81, server: localhost, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/app/apps.sock:", host: "58.180.5.178:43015"
2023/07/28 09:51:27 [crit] 36#36: *4 connect() to unix:/app/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 218.39.165.81, server: localhost, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/app/apps.sock:", host: "58.180.5.178:43015"
2023/07/28 09:51:30 [crit] 36#36: *4 connect() to unix:/app/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 218.39.165.81, server: localhost, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/app/apps.sock:", host: "58.180.5.178:43015"
2023/07/28 09:52:08 [crit] 36#36: *4 connect() to unix:/app/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 218.39.165.81, server: localhost, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/app/apps.sock:", host: "58.180.5.178:43015"
2023/07/28 09:55:22 [crit] 35#35: *9 connect() to unix:/app/apps.sock failed (2: No such file or directory) while connecting to upstream, client: 218.39.165.81, server: localhost, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/app/apps.sock:", host: "58.180.5.178:43015"
